import { useEffect, useState } from "react";
import {
  SonentaProvider,
  useTranslation,
  type Surface,
} from "@sonenta/react-i18next";

/**
 * Surface-variant showcase (task #915) for @sonenta/react-i18next >=1.1.0.
 *
 * A "surface" (desktop / tablet / mobile) is a second resolution dimension
 * layered on top of the locale chain: the base bundle applies to every
 * surface, and a sparse overlay overrides individual keys per surface. With
 * `surfaceBreakpoints`, the provider maps `window.innerWidth` -> surface and
 * calls `setSurface` on resize, so `t()` swaps the value live (no reload).
 *
 * This section runs its OWN isolated SonentaProvider pointed at a
 * demo-hosted, CDN-shaped overlay set (public/surface-cdn/..., generated by
 * scripts/gen-surface-cdn.mjs) — the real demo CDN can't yet author surface
 * overlays. Its locale is synced to the main app's locale.
 */
const SHOWCASE_CDN = `${import.meta.env.BASE_URL}surface-cdn`;

export function SurfaceShowcase() {
  // Read the main app's active locale so the showcase follows the LangSwitcher.
  const { i18n: appI18n } = useTranslation();
  return (
    <section id="surface" className="border-t border-ink-800 bg-ink-900/40">
      <div className="mx-auto max-w-6xl px-6 py-16">
        <div className="mb-8">
          <span className="mono text-[10px] uppercase tracking-[0.22em] text-emerald-400">
            @sonenta/react-i18next · surface variants
          </span>
          <h2 className="mt-2 text-2xl font-semibold tracking-tight text-ink-50">
            One key, the right copy for every screen.
          </h2>
          <p className="mt-2 max-w-2xl text-sm text-ink-300">
            Resize your browser window — the SDK maps the viewport to a{" "}
            <span className="text-ink-100">surface</span> (mobile&nbsp;&lt;640 ·
            tablet&nbsp;&lt;1024 · desktop) and <code className="mono text-emerald-300">t()</code>{" "}
            returns that surface&rsquo;s overlay value in place. No reload, no
            separate keys.
          </p>
        </div>

        <SonentaProvider
          token="surface-demo"
          projectUuid="surface-demo"
          version="v1"
          cdnBase={SHOWCASE_CDN}
          namespaces={["showcase"]}
          defaultLocale={appI18n.locale}
          fallbackLng="en"
          surface="desktop"
          surfaceBreakpoints={true}
          missingHandler="off"
          disableLanguageCatalog
          // Same reason as the root provider: without it, key-style auto-detect
          // fires an authed /versions/ probe that 401s on this public page. The
          // overlays are self-hosted and nested, so "." is the right value.
          keySeparator="."
        >
          <SurfacePanel appLocale={appI18n.locale} />
        </SonentaProvider>
      </div>
    </section>
  );
}

const DeviceIcon = ({ refName }: { refName: string }) => {
  const common = {
    width: 28,
    height: 28,
    viewBox: "0 0 24 24",
    fill: "none",
    stroke: "currentColor",
    strokeWidth: 1.7,
    strokeLinecap: "round" as const,
    strokeLinejoin: "round" as const,
  };
  if (refName === "smartphone")
    return (
      <svg {...common} aria-hidden>
        <rect x="7" y="2" width="10" height="20" rx="2.5" />
        <line x1="11" y1="18" x2="13" y2="18" />
      </svg>
    );
  if (refName === "tablet")
    return (
      <svg {...common} aria-hidden>
        <rect x="5" y="2" width="14" height="20" rx="2.5" />
        <line x1="11" y1="18" x2="13" y2="18" />
      </svg>
    );
  // monitor (desktop)
  return (
    <svg {...common} aria-hidden>
      <rect x="2" y="3" width="20" height="14" rx="2" />
      <line x1="8" y1="21" x2="16" y2="21" />
      <line x1="12" y1="17" x2="12" y2="21" />
    </svg>
  );
};

const SURFACE_META: Record<Surface, { label: string; hint: string }> = {
  mobile: { label: "mobile", hint: "< 640px" },
  tablet: { label: "tablet", hint: "640–1024px" },
  desktop: { label: "desktop", hint: "≥ 1024px" },
};

function SurfacePanel({ appLocale }: { appLocale: string }) {
  const { t, i18n } = useTranslation("showcase");
  const [width, setWidth] = useState(() =>
    typeof window === "undefined" ? 0 : window.innerWidth,
  );

  // Keep the showcase provider's locale in sync with the main app's locale.
  useEffect(() => {
    void i18n.setLocale(appLocale);
  }, [appLocale, i18n]);

  // Live viewport width readout (the SDK drives the actual surface switch via
  // surfaceBreakpoints; this is just for the on-screen px display).
  useEffect(() => {
    const onResize = () => setWidth(window.innerWidth);
    window.addEventListener("resize", onResize);
    return () => window.removeEventListener("resize", onResize);
  }, []);

  const surface: Surface = i18n.surface ?? "desktop";
  const meta = SURFACE_META[surface];
  const asset = i18n.asset("device");
  const SURFACES: Surface[] = ["desktop", "tablet", "mobile"];

  return (
    <div className="rounded-2xl border border-ink-800 bg-ink-900 shadow-[0_1px_0_rgba(255,255,255,0.02),0_24px_60px_-30px_rgba(0,0,0,0.6)] overflow-hidden">
      {/* manual surface toggle — resizing the window does this automatically
          (surfaceBreakpoints), these let you force a surface without resizing */}
      <div className="flex items-center gap-1 px-5 py-3 border-b border-ink-800 bg-ink-950/40">
        <span className="mono text-[10px] uppercase tracking-[0.18em] text-ink-300/60 mr-2">
          surface
        </span>
        <div className="inline-flex items-center gap-1 p-1 rounded-full border border-ink-800 bg-ink-950/60">
          {SURFACES.map((s) => (
            <button
              key={s}
              type="button"
              onClick={() => void i18n.setSurface(s)}
              aria-pressed={surface === s}
              className={[
                "px-3 py-1 text-xs font-medium rounded-full transition-colors capitalize",
                surface === s
                  ? "bg-emerald-400 text-ink-950"
                  : "text-ink-300 hover:text-ink-50",
              ].join(" ")}
            >
              {s}
            </button>
          ))}
        </div>
        <span className="mono text-[10px] text-ink-300/50 ml-auto hidden sm:inline">
          …or just resize the window
        </span>
      </div>

      {/* live surface status bar */}
      <div className="flex flex-wrap items-center gap-3 px-5 py-4 border-b border-ink-800 bg-gradient-to-b from-ink-900 to-ink-900/70">
        <span className="text-emerald-400">
          <DeviceIcon refName={asset?.ref ?? "monitor"} />
        </span>
        <div className="flex flex-col">
          <span className="mono text-[10px] uppercase tracking-[0.18em] text-ink-300">
            active surface
          </span>
          <span className="text-lg font-semibold text-ink-50 leading-tight">
            {t("device")}
          </span>
        </div>
        <span className="mono text-[11px] uppercase tracking-[0.14em] text-ink-950 bg-emerald-400 px-2 py-0.5 rounded-sm">
          {meta.label}
        </span>
        <span className="mono text-xs text-ink-300 ml-auto tabular-nums">
          {width}px <span className="text-ink-300/50">·</span>{" "}
          <span className="text-ink-100">{meta.hint}</span>
        </span>
      </div>

      {/* the string that swaps per surface */}
      <div className="px-5 py-6">
        <span className="mono text-[10px] uppercase tracking-[0.18em] text-ink-300/60 block mb-2">
          t(&quot;banner.message&quot;) · showcase.{surface}.json
        </span>
        <p className="text-lg text-ink-50 leading-snug min-h-[3.5rem]">
          {t("banner.message")}
        </p>
        <button
          type="button"
          className="mt-4 inline-flex items-center rounded-lg bg-emerald-400 px-4 py-2 text-sm font-semibold text-ink-950 hover:bg-emerald-300 transition-colors"
        >
          {t("cta")}
        </button>
      </div>

      {/* asset variant readout */}
      <div className="px-5 py-3 border-t border-ink-800 flex items-center gap-3 text-xs text-ink-300">
        <span className="mono text-[10px] uppercase tracking-[0.18em] text-ink-300/60">
          i18n.asset(&quot;device&quot;)
        </span>
        <code className="mono text-emerald-300">
          {asset ? `{ kind: "${asset.kind}", ref: "${asset.ref}" }` : "—"}
        </code>
        <span className="ml-auto text-ink-300/70">
          per-surface icon, resolved by the SDK
        </span>
      </div>
    </div>
  );
}
